# Generated by Django 2.2.8 on 2020-01-18 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('team', models.CharField(max_length=10)),
                ('nationality', models.CharField(max_length=10)),
                ('price', models.IntegerField()),
                ('actual_score', models.IntegerField(default=0)),
                ('before_play', models.BooleanField(default=True)),
                ('actual_play', models.BooleanField(default=False)),
                ('after_play', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('budget', models.IntegerField(default=500)),
                ('score', models.IntegerField(default=0)),
                ('player1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='player1', to='fantasy_league.Player')),
                ('player2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='player2', to='fantasy_league.Player')),
                ('player3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='player3', to='fantasy_league.Player')),
                ('player4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='player4', to='fantasy_league.Player')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('teams', models.ManyToManyField(to='fantasy_league.Team')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
