# Generated by Django 2.2.8 on 2020-01-21 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_league', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='actual_score',
            new_name='average_score',
        ),
    ]
