# Generated by Django 2.2.8 on 2020-01-18 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_league', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='actual_play',
        ),
        migrations.RemoveField(
            model_name='player',
            name='after_play',
        ),
        migrations.RemoveField(
            model_name='player',
            name='before_play',
        ),
    ]
