# Generated by Django 2.2.6 on 2019-10-27 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_league', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('team', models.CharField(max_length=30)),
                ('nationality', models.CharField(max_length=30)),
                ('price', models.FloatField()),
            ],
        ),
    ]
