# Generated by Django 2.2.8 on 2020-01-18 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_league', '0002_auto_20200118_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
