# Generated by Django 2.2.8 on 2020-01-18 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_league', '0003_auto_20200118_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='name',
            field=models.CharField(max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='league',
            name='password',
            field=models.CharField(max_length=1000),
        ),
    ]
