# Generated by Django 2.2.6 on 2019-11-24 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_league', '0003_auto_20191124_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='user',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='ToDoList',
        ),
    ]
