# Generated by Django 2.2.6 on 2020-01-01 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_league', '0004_auto_20191124_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=6),
        ),
    ]
