# Generated by Django 2.2.6 on 2020-01-01 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_league', '0005_auto_20200101_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='budget',
        ),
    ]
