# Generated by Django 2.2.6 on 2020-01-01 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_league', '0006_remove_team_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=6),
        ),
    ]
