# Generated by Django 2.2.6 on 2020-01-01 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_league', '0007_team_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
