# Generated by Django 2.2.6 on 2020-01-01 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_league', '0009_auto_20200101_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='after_play',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='before_play',
            field=models.BooleanField(default=True),
        ),
    ]
