# Generated by Django 2.2.6 on 2020-01-06 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_league', '0012_league'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
