# Generated by Django 2.2.8 on 2020-01-12 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_league', '0013_auto_20200107_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='teams',
            field=models.ManyToManyField(to='fantasy_league.Team'),
        ),
    ]
